-- =============================================
-- 학습 도메인 테이블 수정 스크립트
-- 실행 순서대로 진행할 것
-- =============================================

-- [1단계] 의존 테이블 먼저 삭제 (FK 순서 역순)
DROP TABLE TBL_QUIZ_RESULT;
DROP SEQUENCE SEQ_QUIZ_RESULT;

DROP TABLE TBL_WORD_STUDY;
DROP SEQUENCE SEQ_WORD_STUDY;

DROP TABLE TBL_TODAY_WORD_RESULT;
DROP SEQUENCE SEQ_TODAY_WORD_RESULT;

DROP TABLE TBL_TODAY_WORD_DETAIL;
DROP SEQUENCE SEQ_TODAY_WORD_DETAIL;

DROP TABLE TBL_TODAY_WORD;
DROP SEQUENCE SEQ_TODAY_WORD;

DROP TABLE TBL_QUIZ_EDU;
DROP SEQUENCE SEQ_QUIZ_EDU;

DROP TABLE TBL_QUIZ_QUESTION;
DROP SEQUENCE SEQ_QUIZ_QUESTION;

DROP TABLE TBL_EDU_WORD;
DROP SEQUENCE SEQ_EDU_WORD;

-- [2단계] 기존 테이블 컬럼 수정
-- TBL_EDU: 설명 컬럼 1000자로 확장
ALTER TABLE TBL_EDU MODIFY EDU_DETAIL VARCHAR2(1000);

-- TBL_EDU_START: FK 컬럼 NOT NULL
ALTER TABLE TBL_EDU_START MODIFY USER_ID NOT NULL;
ALTER TABLE TBL_EDU_START MODIFY EDU_ID NOT NULL;

-- TBL_EDU_VIDEO: URL 컬럼 1000자로 확장
ALTER TABLE TBL_EDU_VIDEO MODIFY EDU_VIDEO_URL VARCHAR2(1000);

-- TBL_EDU_CERT: FK 컬럼 NOT NULL
ALTER TABLE TBL_EDU_CERT MODIFY EDU_ID NOT NULL;
ALTER TABLE TBL_EDU_CERT MODIFY USER_ID NOT NULL;

-- TBL_USER_ATTENDANCE: 날짜 컬럼 추가
ALTER TABLE TBL_USER_ATTENDANCE ADD USER_ATTENDANCE_DATE DATE DEFAULT TRUNC(SYSDATE) NOT NULL;
ALTER TABLE TBL_USER_ATTENDANCE MODIFY USER_ID NOT NULL;

-- [3단계] TBL_EDU_WORD_MAP 신규 생성 (기존 TBL_EDU_WORD 대체)
CREATE SEQUENCE SEQ_EDU_WORD_MAP;
CREATE TABLE TBL_EDU_WORD_MAP(
    ID NUMBER CONSTRAINT PK_EDU_WORD_MAP PRIMARY KEY,
    EDU_ID NUMBER NOT NULL,
    WORDS_ID NUMBER NOT NULL,
    CONSTRAINT FK_EDU_WORD_MAP_EDU FOREIGN KEY (EDU_ID)
        REFERENCES TBL_EDU(ID),
    CONSTRAINT FK_EDU_WORD_MAP_WORDS FOREIGN KEY (WORDS_ID)
        REFERENCES TBL_WORDS(ID)
);

-- [4단계] TBL_QUIZ_QUESTION 재생성 (FK 변경: EDU_WORDS_ID -> WORDS_ID)
CREATE SEQUENCE SEQ_QUIZ_QUESTION;
CREATE TABLE TBL_QUIZ_QUESTION(
    ID NUMBER CONSTRAINT PK_QUIZ_QUESTION PRIMARY KEY,
    QUIZ_QUESTION_TYPE VARCHAR2(255) NOT NULL,
    QUIZ_QUESTION_DETAIL VARCHAR2(255) NOT NULL,
    QUIZ_QUESTION_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    WORDS_ID NUMBER NOT NULL,
    CONSTRAINT FK_QUIZ_QUESTION_WORDS FOREIGN KEY (WORDS_ID)
        REFERENCES TBL_WORDS(ID)
);

-- [5단계] TBL_QUIZ_CHOICE 재생성
CREATE SEQUENCE SEQ_QUIZ_CHOICE;
CREATE TABLE TBL_QUIZ_CHOICE(
    ID NUMBER CONSTRAINT PK_QUIZ_CHOICE PRIMARY KEY,
    QUIZ_CHOICE_NUMBER NUMBER NOT NULL,
    QUIZ_CHOICE_IS_CORRECT NUMBER DEFAULT 0 NOT NULL,
    QUIZ_CHOICE_DETAIL VARCHAR2(255) NOT NULL,
    QUIZ_QUESTION_ID NUMBER NOT NULL,
    CONSTRAINT FK_QUIZ_CHOICE_QUIZ_QUESTION FOREIGN KEY (QUIZ_QUESTION_ID)
        REFERENCES TBL_QUIZ_QUESTION(ID)
);

-- [6단계] TBL_TODAY_WORD 재생성 (날짜 컬럼 추가)
CREATE SEQUENCE SEQ_TODAY_WORD;
CREATE TABLE TBL_TODAY_WORD(
    ID NUMBER CONSTRAINT PK_TODAY_WORD PRIMARY KEY,
    TODAY_WORD_DATE DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    TODAY_WORD_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT FK_TODAY_WORD_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER(ID)
);

-- [7단계] TBL_TODAY_WORD_DETAIL 재생성
CREATE SEQUENCE SEQ_TODAY_WORD_DETAIL;
CREATE TABLE TBL_TODAY_WORD_DETAIL(
    ID NUMBER CONSTRAINT PK_TODAY_WORD_DETAIL PRIMARY KEY,
    TODAY_WORD_ID NUMBER NOT NULL,
    QUIZ_QUESTION_ID NUMBER NOT NULL,
    CONSTRAINT FK_TODAY_WORD_DETAIL_TODAY_WORD FOREIGN KEY (TODAY_WORD_ID)
        REFERENCES TBL_TODAY_WORD(ID),
    CONSTRAINT FK_TODAY_WORD_DETAIL_QUIZ_QUESTION FOREIGN KEY (QUIZ_QUESTION_ID)
        REFERENCES TBL_QUIZ_QUESTION(ID)
);

-- [8단계] TBL_TODAY_WORD_RESULT 재생성 (선택 보기 ID + 정답여부 저장)
CREATE SEQUENCE SEQ_TODAY_WORD_RESULT;
CREATE TABLE TBL_TODAY_WORD_RESULT(
    ID NUMBER CONSTRAINT PK_TODAY_WORD_RESULT PRIMARY KEY,
    TODAY_WORD_RESULT_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TODAY_WORD_RESULT_IS_CORRECT NUMBER DEFAULT 0 NOT NULL,
    TODAY_WORD_DETAIL_ID NUMBER NOT NULL,
    QUIZ_CHOICE_ID NUMBER NOT NULL,
    CONSTRAINT FK_TODAY_WORD_RESULT_TODAY_WORD_DETAIL FOREIGN KEY (TODAY_WORD_DETAIL_ID)
        REFERENCES TBL_TODAY_WORD_DETAIL(ID),
    CONSTRAINT FK_TODAY_WORD_RESULT_CHOICE FOREIGN KEY (QUIZ_CHOICE_ID)
        REFERENCES TBL_QUIZ_CHOICE(ID)
);

-- [9단계] TBL_QUIZ_EDU 재생성 (NOT NULL 추가)
CREATE SEQUENCE SEQ_QUIZ_EDU;
CREATE TABLE TBL_QUIZ_EDU(
    ID NUMBER CONSTRAINT PK_QUIZ_EDU PRIMARY KEY,
    QUIZ_ID NUMBER NOT NULL,
    QUIZ_QUESTION_ID NUMBER NOT NULL,
    CONSTRAINT FK_QUIZ_EDU_QUIZ FOREIGN KEY (QUIZ_ID)
        REFERENCES TBL_QUIZ(ID),
    CONSTRAINT FK_QUIZ_EDU_QUIZ_QUESTION FOREIGN KEY (QUIZ_QUESTION_ID)
        REFERENCES TBL_QUIZ_QUESTION(ID)
);

-- [10단계] TBL_QUIZ_ATTEMPT 신규 생성 (기존 TBL_QUIZ_RESULT 대체)
CREATE SEQUENCE SEQ_QUIZ_ATTEMPT;
CREATE TABLE TBL_QUIZ_ATTEMPT(
    ID NUMBER CONSTRAINT PK_QUIZ_ATTEMPT PRIMARY KEY,
    QUIZ_ATTEMPT_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    QUIZ_ATTEMPT_SCORE NUMBER DEFAULT 0 NOT NULL,
    QUIZ_ATTEMPT_TOTAL_COUNT NUMBER DEFAULT 0 NOT NULL,
    USER_ID NUMBER NOT NULL,
    QUIZ_ID NUMBER NOT NULL,
    CONSTRAINT FK_QUIZ_ATTEMPT_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER(ID),
    CONSTRAINT FK_QUIZ_ATTEMPT_QUIZ FOREIGN KEY (QUIZ_ID)
        REFERENCES TBL_QUIZ(ID)
);

-- [11단계] TBL_QUIZ_ATTEMPT_DETAIL 신규 생성
CREATE SEQUENCE SEQ_QUIZ_ATTEMPT_DETAIL;
CREATE TABLE TBL_QUIZ_ATTEMPT_DETAIL(
    ID NUMBER CONSTRAINT PK_QUIZ_ATTEMPT_DETAIL PRIMARY KEY,
    QUIZ_ATTEMPT_ID NUMBER NOT NULL,
    QUIZ_QUESTION_ID NUMBER NOT NULL,
    QUIZ_CHOICE_ID NUMBER NOT NULL,
    QUIZ_ATTEMPT_DETAIL_IS_CORRECT NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT FK_QUIZ_ATTEMPT_DETAIL_ATTEMPT FOREIGN KEY (QUIZ_ATTEMPT_ID)
        REFERENCES TBL_QUIZ_ATTEMPT(ID),
    CONSTRAINT FK_QUIZ_ATTEMPT_DETAIL_QUESTION FOREIGN KEY (QUIZ_QUESTION_ID)
        REFERENCES TBL_QUIZ_QUESTION(ID),
    CONSTRAINT FK_QUIZ_ATTEMPT_DETAIL_CHOICE FOREIGN KEY (QUIZ_CHOICE_ID)
        REFERENCES TBL_QUIZ_CHOICE(ID)
);

-- [12단계] TBL_WORD_STUDY 재생성 (컬럼 추가 및 FK 변경)
CREATE SEQUENCE SEQ_WORD_STUDY;
CREATE TABLE TBL_WORD_STUDY(
    ID NUMBER CONSTRAINT PK_WORD_STUDY PRIMARY KEY,
    WORD_STUDY_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    WORD_STUDY_UPDATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    WORD_STUDY_IS_COMPLETED NUMBER DEFAULT 0 NOT NULL,
    EDU_WORD_MAP_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT FK_WORD_STUDY_EDU_WORD_MAP FOREIGN KEY (EDU_WORD_MAP_ID)
        REFERENCES TBL_EDU_WORD_MAP(ID),
    CONSTRAINT FK_WORD_STUDY_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER(ID)
);
